### ISSUE TITLE
OO Results set

### ISSUE THREAD

**Issue by BrunoSanchez** [quatrope/feets#7]
Implement a new result container, possible an object.

It should include features with arbitrary structure, and focusing on 
readability of the results. 
An example would be to generate visualization for features with a common background, 
such as fourier components, or statistical moments.

It should have a method `.as_array()` which shall return the previous output.

**Comment by leliel12** [comment]
Examples

```python

fs = FeatureSpace()
rset = fs.extract(...)

# list available features
rset.ls()

# to get the same iput
features, values = rset.as_array()

# plot some feature
rset.plot("fourier")
rset.plot("signatures")
```

**Comment by leliel12** [comment]
the api was changed to

```python
rset.as_arrays()
```

**Comment by leliel12** [comment]
The object currently returns a resultset the plot is still ongoing
